kafka:
  brokers: "172.18.0.2:9092"
  topic: "web-crawl-urls"

kvstore:
  path: "/home/red/projects/search/web-crawler/data/kvstore.db"

storage:
  path: "/home/red/projects/search/web-crawler/data/storage"
